### ISSUE TITLE
[FEAT] Feed 게시글 목록 View UI

### ISSUE THREAD

**Issue by dy-yb** [BorryJJong/KnockKnock-iOS#17]
## **💡 Issue**
- 피드 게시글 목록 View UI를 구성합니다. (검색 화면은 제외, 이미지만 모여서 보이는 가장 최상단 리스트)

## **📝 todo**
- 각 뷰에 필요한 ui들을 정의하고, 디자인에 따른 대략적인 Autolayout을 구성합니다.

**Comment by feelsodev** [comment]
작업 완료 👍 
고생하셨습니다 ~ @dy-yb
