### ISSUE TITLE
[개선] 로그아웃 버튼 클릭시 인지버튼 추가

### ISSUE THREAD

**Issue by hiYong94** [BorryJJong/KnockKnock-iOS#262]
### [버전]
3월14일 16:24분 배포 버전

### [설명]
- 사용자 로그아웃 버튼 클릭시, 바로 로그아웃이 되어 사용자 인지가 부족함

**Comment by hiYong94** [comment]
@dy-yb 해당 개선 이슈는 적용되면 좋을 것 같습니다

**Comment by dy-yb** [comment]
로그아웃 버튼 클릭시 재 확인용 alert 정도면 충분할까요? 혹은 완료 이후에 '로그아웃 되었습니다' 메세지가 필요하다고 보시나요?

**Comment by hiYong94** [comment]
@dy-yb 저는 후자가 좀 더 좋다고 생각하는데, 두 가지 방식모두 인지가 필요한 것에 충족되기때문에 다예님이 편한 작업으로 선택해주시면될 것 같습니다!

"탈퇴하기"는 인지적용이 잘되있는 것 같아 좋습니다
