### ISSUE TITLE
[FEAT] 공지사항 목록/상세 화면 layout

### ISSUE THREAD

**Issue by dy-yb** [BorryJJong/KnockKnock-iOS#98]
## **💡 Issue**
- 공지사항 리스트 화면과 상세 화면을 구성합니다.

## **📝 todo**
- 디자인에 맞게 ui를 구성하고 autolayout을 설정합니다.

**Comment by feelsodev** [comment]
@dy-yb 
생각하고 보니 이슈사항에 디자인 내용도 첨부하면 좋을 것 같네요?
